      - name: Patch Gradle for Kotlin 2.0 Compose
        run: |
          cat > app/build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
              id("org.jetbrains.kotlin.plugin.compose") version "2.0.0"   // <-- add version
              id("org.jetbrains.kotlin.plugin.serialization")
          }

          android {
              namespace = "com.example.dailyspendgame"
              compileSdk = 34

              defaultConfig {
                  applicationId = "com.example.dailyspendgame"
                  minSdk = 26
                  targetSdk = 34
                  versionCode = 2
                  versionName = "1.1.0"
                  testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
                  vectorDrawables { useSupportLibrary = true }
              }

              buildTypes {
                  release {
                      isMinifyEnabled = true
                      proguardFiles(
                          getDefaultProguardFile("proguard-android-optimize.txt"),
                          "proguard-rules.pro"
                      )
                  }
                  debug { isMinifyEnabled = false }
              }

              buildFeatures { compose = true; buildConfig = true }

              // No composeOptions block when using Kotlin 2.0 + compose plugin
              packaging { resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" } }
              kotlinOptions { jvmTarget = "17" }
          }

          dependencies {
              val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
              implementation(composeBom)
              androidTestImplementation(composeBom)

              implementation("androidx.core:core-ktx:1.13.1")
              implementation("androidx.activity:activity-compose:1.9.1")
              implementation("androidx.compose.ui:ui")
              implementation("androidx.compose.material3:material3")
              implementation("androidx.compose.ui:ui-tooling-preview")
              debugImplementation("androidx.compose.ui:ui-tooling")
              implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")

              implementation("androidx.datastore:datastore-preferences:1.1.1")
              implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")

              testImplementation("junit:junit:4.13.2")
              androidTestImplementation("androidx.test.ext:junit:1.2.1")
              androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
              androidTestImplementation("androidx.compose.ui:ui-test-junit4")
          }
          EOF
