name: Build Debug APK

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you only uploaded the ZIP, unzip it into the repo root
      - name: Ensure project files are present
        run: |
          if [ -f "DailySpendGame_Revamped_v2.zip" ]; then
            unzip -o DailySpendGame_Revamped_v2.zip -d .
          fi
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --licenses <<<"y" >/dev/null
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Project doesn’t include gradle wrapper; download Gradle
      - name: Download Gradle 8.7
        run: |
          curl -sL -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DailySpendGame-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
